Repository camaraproject/APIBacklog, pull requests merged in 2024-06, with the labels that each got.

#39 New API Proposal Device_Volume_indicator.md
  documentation/API proposals/APIProposa_Device_Volume.md
Labels: API Proposal

#47 API name change - from RegionUserCount to RegionDeviceCount
  documentation/API proposals/APIproposal_RegionDeviceCount_ChinaUnicom.md
  documentation/API proposals/APIproposal_RegionUserCount_ChinaUnicom.md
  documentation/APIbacklog.md
Labels: Scope Enhancement

#62 Update APIbacklog.md
  documentation/APIbacklog.md
Labels: subproject management
